---
title: "create-matrix"
author: "AndrewJ"
date: "13 July 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

# Description

Generate a Markov chain transition probability matrix from given text, to be used as input to a password generator in Javascript.

# Setup

```{r echo = FALSE, message = FALSE, results = FALSE}
library(tidyverse)
library(tidytext)
library(stringr)
library(markovchain)
library(gutenbergr)
```

# Read in all sample text

```{r}
#txt_raw <- read_lines("input.txt") %>%
#  tibble(line = 1:length(.), text = .) %>%
#  unnest_tokens(word, text, token = "words")
```

# Source text from Project Gutenberg
```{r}
hgwells <- gutenberg_download(c(35, 36, 5230, 159))
```

```{r}
txt <- 
  hgwells %>%
  unnest_tokens(char, text)
```

# Generate transition matrix

Split into characters, but keep inter-word spaces.
```{r}
chars <- txt %>%
  pull(char) %>%
  str_replace("[0-9,.\\-']+", "") %>%
  str_replace("$", " ") %>%
  str_c(collapse = '') %>%
  str_split("") %>%
  unlist

chain <- markovchainFit(chars, method = "mle")
transitions <- chain$estimate@transitionMatrix
```

# Visualise

First, turn from wide to "tidy" format
```{r}
trans_tbl <- as_tibble(transitions) %>%
  mutate(Source = row.names(transitions)) %>%
  gather(key = Target, value = Probability, ` `:z)
```

Heat map
```{r}
trans_tbl %>%
  ggplot(aes(x = Source, y = Target)) +
  geom_raster(aes(fill = Probability))
```

# Export

```{r}
transitions %>%
  t %>%
  write(file = "transitions.txt", ncolumns = nrow(.), sep = ",")
```

